trigger:
  - feature/terraform-apply

pool:
  name: Agent007

stages:
  - stage: "InitalCheckup"
    displayName: "Inital Checkup"

    jobs:
      - job: "terraformPlan"
        displayName: "Working till Planning"

        steps:
          - task: TerraformInstaller@1
            displayName: "Installing Terraform"

          - script: terraform version
            displayName: "Checking Version"

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)\Parent-Module\Dev'
              backendServiceArm: 'agent-azlz-pr1'
              backendAzureRmOverrideSubscriptionID: 'ec2a3393-5658-4171-90d5-1188fd9f69d6'
              backendAzureRmResourceGroupName: 'ut-backup-rg'
              backendAzureRmStorageAccountName: 'backupstg007'
              backendAzureRmContainerName: 'aod-storage'
              backendAzureRmKey: 'dev/terraform.tfstate'
            env:
              ARM_ACCESS_KEY: $(storage_access_key)
          
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)\Parent-Module\Dev'
          
          - task: TerraformTaskV4@4
            displayName: "running plan"  
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'agent-azlz-pr1'
              workingDirectory: '$(System.DefaultWorkingDirectory)\Parent-Module\Dev'
            env:
              TF_VAR_admin_username: $(admin_username)
              TF_VAR_admin_password: $(admin_password) 