trigger:
- main

pool:
  name: Agent007

stages:
- stage: TerraformPlan
  displayName: 'Terraform Init Validate Plan'
  jobs:
  - job: Terraform
    displayName: 'Terraform'
    steps:

    - task: TerraformInstaller@1
      displayName: 'Terraform Install'
      inputs:
        terraformVersion: 'Latest'
    

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'agent-azlz-pr1'
        workingDirectory: '$(System.DefaultWorkingDirectory)\Parent-Module'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)\Parent-Module'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'agent-azlz-pr1'
        workingDirectory: '$(System.DefaultWorkingDirectory)\Parent-Module'